esphome:
  name: heltec-v3
  friendly_name: Heltec v3
  on_boot:
    priority: -100
    then:
      - delay: 180s

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "3rd5jOfvEODwn0yfzM/kVY5UMhZeE+r0EP9sipT2ZGY="

ota:
  - platform: esphome
    password: "41706f325981038183fc7981cedbd2ec"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Heltec-V3 Fallback Hotspot"
    password: "na6BUIFDHNpn"

captive_portal:
one_wire:
  - platform: gpio
    pin: GPIO4
sensor:
  - platform: dallas_temp
    name: "Flow Temperature"
    id: flow_temp
    index: 0
    update_interval: 60s
    accuracy_decimals: 1
  - platform: dallas_temp
    name: "Return Temperature"
    id: return_temp
    index: 1
    update_interval: 60s
    accuracy_decimals: 1