esphome:
  name: ESP8266
  friendly_name: ESP8266

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "aU3nSpdlXKX/O0hkIO30dNO/uQB76Y73IZjQQ12jzwc="

ota:
  - platform: esphome
    password: "7c0f979dd151805cc9001c6801d7c54a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wifi Fallback Hotspot"
    password: "DgNoPJEvMrVK"

captive_portal:

# Web server for viewing sensor data directly (optional)
web_server:
  port: 80

one_wire:
  - platform: gpio
    pin: GPIO2

sensor:
  - platform: dallas_temp
    name: "Flow Temperature"
    id: flow_temp
    index: 0
    update_interval: 30s
    accuracy_decimals: 1
  - platform: dallas_temp
    name: "Return Temperature"
    id: return_temp
    index: 1
    update_interval: 30s
    accuracy_decimals: 1
  - platform: uptime
    name: "Temperature Monitor Uptime"
    update_interval: 60s

