esphome:
  name: heltec-v3
  friendly_name: Heltec v3
  on_boot:
    priority: -100
    then:
      - delay: 180s
      - lambda: id(oled_display).turn_off();

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "3rd5jOfvEODwn0yfzM/kVY5UMhZeE+r0EP9sipT2ZGY="

ota:
  - platform: esphome
    password: "41706f325981038183fc7981cedbd2ec"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Heltec-V3 Fallback Hotspot"
    password: "na6BUIFDHNpn"

captive_portal:

i2c:
  sda: GPIO17
  scl: GPIO18
  frequency: 400kHz
  scan: true

one_wire:
  - platform: gpio
    pin: GPIO4

font:
  - file: "gfonts://Roboto@700"
    id: font_temp
    size: 18

sensor:
  - platform: dallas_temp
    name: "Flow Temperature"
    id: flow_temp
    index: 0
    update_interval: 60s
    accuracy_decimals: 1
  - platform: dallas_temp
    name: "Return Temperature"
    id: return_temp
    index: 1
    update_interval: 60s
    accuracy_decimals: 1

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    reset_pin: GPIO21
    id: oled_display
    update_interval: 10s
    lambda: |-
      float flow = id(flow_temp).state;
      if (isnan(flow)) {
        it.printf(64, 10, id(font_temp), TextAlign::CENTER, "Flow: --.-째C");
      } else {
        it.printf(64, 10, id(font_temp), TextAlign::CENTER, "Flow: %.1f째C", flow);
      }

      float ret = id(return_temp).state;
      if (isnan(ret)) {
        it.printf(64, 38, id(font_temp), TextAlign::CENTER, "Return: --.-째C");
      } else {
        it.printf(64, 38, id(font_temp), TextAlign::CENTER, "Return: %.1f째C", ret);
      }