esphome:
  name: esphome-web-00680a
  friendly_name: ESPHome Pi
  min_version: 2025.11.0
  name_add_mac_suffix: false

rp2040:
  board: rpipicow

logger:

api:

ota:
  platform: esphome

wifi:
  networks:
    - ssid: !secret warfield_ssid
      password: !secret warfield_password
    - ssid: !secret gchq_ssid
      password: !secret gchq_password

time:
  - platform: sntp
    id: ha_time
    timezone: Europe/London

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: false   # set to true temporarily to confirm BME280 & OLED addresses

font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 10

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 30s
    lambda: |-
      auto now = id(ha_time).now();
      it.strftime(0, 0, id(font_small), TextAlign::TOP_LEFT, "%H:%M:%S", now);
      it.strftime(0, 12, id(font_small), TextAlign::TOP_LEFT, "%d/%m/%Y", now);
      it.printf(0, 26, id(font_small), TextAlign::TOP_LEFT, "Temp: %.1f °C", id(pico_temp).state);
      it.printf(0, 38, id(font_small), TextAlign::TOP_LEFT, "Hum:  %.0f %%", id(pico_hum).state);
      it.printf(0, 50, id(font_small), TextAlign::TOP_LEFT, "Pres: %.0f hPa", id(pico_pressure).state);

sensor:
  - platform: bme280_i2c
    address: 0x76               # change to 0x77 if no readings appear
    temperature:
      id: pico_temp
      name: "Pico W Temperature"
    pressure:
      id: pico_pressure
      name: "Pico W Pressure"
    humidity:
      id: pico_hum
      name: "Pico W Humidity"
    update_interval: 60s

interval:
  - interval: 5s
    then:
      - logger.log:
          format: "Temperature: %.1f °C | Humidity: %.1f %% | Pressure: %.1f hPa"
          args: [id(pico_temp).state, id(pico_hum).state, id(pico_pressure).state]

# === All LED-related code is commented out below ===

#output:
#  - platform: gpio
#    pin: 32
#    id: onboard_led

#light:
#  - platform: binary
#    name: "Onboard LED"
#    id: onboard_led_light
#    output: onboard_led

#interval:
#  - interval: 1s
#    then:
#      - light.toggle: onboard_led_light
